- hosts: undercloud
  tasks:
  - name: Delete overcloud deployment, if it exists
    shell: |
      source ~/stackrc && openstack overcloud delete overcloud -y
    ignore_errors: yes
    
  - name: Deploy overcloud
    shell: |
      source ~/stackrc && ./overcloud_deploy.sh > ~/overcloud_install.log 2>&1
